package canonicaljson

import (
	"encoding/json"
	"os"
	"testing"
)

// TestParityWithUpstreamStringify checks the Go canonical writer against
// vectors produced by the real ECMAScript engine (testdata generated by
// running deep-sort + JSON.stringify in node — the same algorithm as
// @decionis/verify's stableJsonStringify). Byte-for-byte parity here is what
// makes Ed25519 dossier verification in Go trustworthy.
func TestParityWithUpstreamStringify(t *testing.T) {
	raw, err := os.ReadFile("testdata/canonical-vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var vectors []struct {
		Input    string `json:"input"`
		Expected string `json:"expected"`
	}
	if err := json.Unmarshal(raw, &vectors); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	if len(vectors) == 0 {
		t.Fatal("no vectors loaded")
	}
	for i, vector := range vectors {
		value, err := Decode([]byte(vector.Input))
		if err != nil {
			t.Fatalf("vector %d: decode: %v", i, err)
		}
		got, err := Stringify(value)
		if err != nil {
			t.Fatalf("vector %d: stringify: %v", i, err)
		}
		if got != vector.Expected {
			t.Errorf("vector %d parity failure:\n input:    %s\n expected: %s\n got:      %s",
				i, vector.Input, vector.Expected, got)
		}
	}
}

func TestStringifyRejectsUndeclaredTypes(t *testing.T) {
	if _, err := Stringify(map[string]any{"n": float64(1)}); err == nil {
		t.Fatal("float64 must be rejected — numbers must arrive as json.Number via Decode")
	}
	if _, err := Stringify(map[string]any{"n": 1}); err == nil {
		t.Fatal("int must be rejected — numbers must arrive as json.Number via Decode")
	}
}
